@echo off
echo Building Issue 4 (Mutex Baseline Engine) in Titanium...
g++ -O3 -std=c++17 baseline_benchmark.cpp baseline_engine.cpp order_generator.cpp -o baseline_benchmark.exe
echo Build Complete! Running benchmark...
.\baseline_benchmark.exe